import type { ThumbnailPage } from './lib/schema.mjs';

/**
 * Default wording used by the template. Every section heading can be replaced
 * per page with the optional "headings" field of the content file.
 */

const NUMBER_WORDS = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'];

export function numberWord(n: number, capitalise = false): string {
  const w = n >= 0 && n <= 10 ? NUMBER_WORDS[n] : String(n);
  return capitalise ? w.charAt(0).toUpperCase() + w.slice(1) : w;
}

/** "Fortnite-style", "MrBeast-style" (kept as is), "Podcast" (genres are not a style). */
export function lookName(page: Pick<ThumbnailPage, 'name' | 'category'>): string {
  if (page.category === 'genre') return page.name;
  return /[-\s]style$/i.test(page.name) ? page.name : `${page.name}-style`;
}

/** "a" or "an" before a word (simple vowel rule; override with cta.label when it reads wrong). */
export function article(word: string): string {
  return /^[aeiou]/i.test(word) ? 'an' : 'a';
}

export function defaultHeadings(page: ThumbnailPage) {
  const look = lookName(page);
  const count = page.gallery.length;
  const isStyle = /[-\s]style$/i.test(page.name);
  return {
    gallery: `${count} ${look} thumbnail examples`,
    recipe: isStyle ? `The ${page.name} look, rule by rule` : `The ${page.name} thumbnail style, rule by rule`,
    layouts: `${numberWord(page.layouts.length, true)} layouts for ${page.name} thumbnails`,
    guide: `How to make ${article(page.name)} ${page.name} thumbnail`,
    dos: 'Do this, not that',
    faq: `Questions about ${page.name} thumbnails`,
    related: 'More thumbnail ideas',
    listing: 'Pick a page',
    ...page.headings,
  };
}

export function examplesNote(page: Pick<ThumbnailPage, 'category'>): string {
  return page.category === 'game'
    ? 'Every example is an original image generated with Base.Tube: no game art, logos, screenshots or real people. Select one to see the prompt behind it.'
    : 'Every example is an original image generated with Base.Tube: no real people, logos or copied thumbnails. Select one to see the prompt behind it.';
}

export function disclaimerText(page: Pick<ThumbnailPage, 'trademark' | 'category'>): string {
  const own =
    page.category === 'game'
      ? 'Every example on this page is an original image generated by Base.Tube: no game art, logos, screenshots or real people.'
      : 'Every example on this page is an original image generated by Base.Tube: no real people, logos or copies of existing thumbnails.';
  if (!page.trademark) return own;
  const { name, owner } = page.trademark;
  const whose = owner ? `a trademark of ${owner}` : 'a trademark of its owner';
  const notWith = owner || `the owner of ${name}`;
  const end = notWith.endsWith('.') ? '' : '.';
  return `${name} is ${whose}, used here only to describe a visual style. Base.Tube is not affiliated with, sponsored or endorsed by ${notWith}${end} ${own}`;
}

export function formatDate(iso: string): string {
  const d = new Date(`${iso}T00:00:00Z`);
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });
}
